/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.archetype.Package;

import java.util.*;
import java.time.*;

// ----------- << imports@AAAAAAGFyo0wz6uwd1E= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFyo0wz6uwd1E= >>
// ----------- >>
public class Dipendente extends User {
	// ----------- << attribute.annotations@AAAAAAGFyqaIt8hNeEs= >>
	// ----------- >>
	private ArrayList<Dipendente> ListaDipendenti;

	@Override
	public ListaDipendenti get() {
		return;
	}

	@Override
	public void set(ListaDipendenti ) {
        this. = ;
    }

	public void link(ListaDipendenti _) {
		if (_ != null) {
			_.get().add(this);
		}

		unlink();
		set(_);
	}

	@Override
	public void unlink() {
		if (get() != null) {
			get().get().remove(this);
			set(null);
		}
	}

	// ----------- << method.annotations@AAAAAAGFyq+YOdW3jAQ= >>
	// ----------- >>
	public void InserisciDDT() {
		// ----------- << method.body@AAAAAAGFyq+YOdW3jAQ= >>
		// ----------- >>
	}
// ----------- << class.extras@AAAAAAGFyo0wz6uwd1E= >>
// ----------- >>
}