/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.archetype.Package;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGFyo3C16vtYQ0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFyo3C16vtYQ0= >>
// ----------- >>
public class Proprietario extends User {
    // ----------- << method.annotations@AAAAAAGFyqFK0seCVW8= >>
    // ----------- >>
    public void assignPassword() {
    // ----------- << method.body@AAAAAAGFyqFK0seCVW8= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGFyqKgWseZ7kc= >>
    // ----------- >>
    public void addFornitore() {
    // ----------- << method.body@AAAAAAGFyqKgWseZ7kc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGFyqO05cegbYU= >>
    // ----------- >>
    public void assumiDipendente() {
    // ----------- << method.body@AAAAAAGFyqO05cegbYU= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGFyo3C16vtYQ0= >>
// ----------- >>
}