/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.archetype.Package;

// ----------- << imports@AAAAAAGGDxl/kddqeIM= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGGDxl/kddqeIM= >>
// ----------- >>
public class DDT { // viene generato al momento della CONSEGNA dell'ordine

	private long numeroOrdine;

	public DDT(long numeroOrdine) {
		this.numeroOrdine = numeroOrdine;
	}

	// gettersandsetters
	public long getNumeroOrdine() {
		return numeroOrdine;
	}

// ----------- << class.extras@AAAAAAGGDxl/kddqeIM= >>
// ----------- >>
}