/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.archetype.Package;

import prog.utili.Data;

// ----------- << imports@AAAAAAGGDNnZxFU2izo= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGGDNnZxFU2izo= >>
// ----------- >>
public class Prodotto {

	private String IDprodotto;
	private int qta;
	private String nome;
	private Data scadenza;

	public Prodotto(String ID, int qta, String nome, Data scadenza) {
		this.IDprodotto = ID;
		this.qta = qta;
		this.nome = nome;
		this.scadenza = scadenza;
	}

	public String getIDprodotto() {
		return IDprodotto;
	}

	public int getQta() {
		return qta;
	}

	public String getNome() {
		return nome;
	}

	public Data getScadenza() {
		return scadenza;
	}

	public void setQta(int qta) {
		this.qta = qta;
	}

// ----------- << class.extras@AAAAAAGGDNnZxFU2izo= >>
// ----------- >>
}