/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package persone;

public class Dipendente extends User {

	public Dipendente(String UserID, String Nome, String Cognome, String Password) {
		super(UserID, Nome, Cognome, Password);
	}

// ----------- << class.extras@AAAAAAGFyo0wz6uwd1E= >>
// ----------- >>

}