/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package persone;

import com.archetype.Package.Ordine;
import com.archetype.Package.StatoOrdine;

// ----------- << imports@AAAAAAGFyqAZ/sdD2+M= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFyqAZ/sdD2+M= >>
// ----------- >>
public class Fornitore {

	private String Nome;
	private String codiceFornitore;

	public Fornitore(String Nome, String codiceFornitore) {
		this.Nome = Nome;
		this.codiceFornitore = codiceFornitore;
	}

	// getters and setters
	public String getNome() {
		return Nome;
	}

	public String getCodiceFornitore() {
		return codiceFornitore;
	}

	// methods
	public void confermaOrdine(Ordine ordine) {
		ordine.setStatoOrdine(StatoOrdine.CONFERMATO);
	}

	public void consegnaOrdine(Ordine ordine) {
		ordine.setStatoOrdine(StatoOrdine.CONSEGNATO);
	}

	public void inoltroOrdine(Ordine ordine) {
		ordine.setStatoOrdine(StatoOrdine.INOLTRATO);
	}

	public boolean checkDisponibilita(Ordine ordine) {
		return false;

	}

// ----------- << class.extras@AAAAAAGFyqAZ/sdD2+M= >>
// ----------- >>
}