/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package persone;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import connectingdb.Connectiontest;

// ----------- << imports@AAAAAAGFyotJtauBLeE= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFyotJtauBLeE= >>
// ----------- >>
public class User {

	private String UserID;
	private String Nome;
	private String Cognome;
	private String Password;

	public User(String UserID, String Nome, String Cognome, String Password) {
		this.UserID = UserID;
		this.Nome = Nome;
		this.Cognome = Cognome;
		this.Password = Password;
	}

	public User(String nome, String password) {
		this.Nome = nome;
		this.Password = password;
	}

	// gettersandsetters
	public String getUserID() {
		return UserID;
	}

	public String getNome() {
		return Nome;
	}

	public String getCognome() {
		return Cognome;
	}

	public String getPassword() {
		return Password;
	}

	public void setPassword(String password) {
		Password = password;
	}

	// methods
	public void nuovoOrdine() {

	}

	public void visualizzaOrdini() {

	}

	public String visualizzaGiacenze() { // ACCESSO A DB
		String string = "Prodotti: \n";
		Connectiontest ct = new Connectiontest(
				"C:\\Users\\megan\\OneDrive\\Documents\\GitHub\\EasyDhack\\DhackFar\\localdb.db");
		ct.connect();

		try {
			ct.setStatement(ct.getConnection().createStatement());
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}

		ResultSet resultSet = null;
		String query = "SELECT ProdottoID, Nome, Quantità FROM Magazzino";
		try {
			resultSet = ct.getStatement().executeQuery(query);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		try {
			while (resultSet.next()) {
				string = string.concat("Id: " + resultSet.getString("ProdottoID") + "| Nome: "
						+ resultSet.getString("Nome") + "| Quantità: " + resultSet.getInt("Quantità") + "\n");

			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		ct.close();
		return string;

	}

	public void visualizzaScadenze() { // ACCESSO A DB
		Connectiontest ct = new Connectiontest(
				"C:\\Users\\megan\\OneDrive\\Documents\\GitHub\\EasyDhack\\DhackFar\\localdb.db");
		ct.connect();

		try {
			ct.setStatement(ct.getConnection().createStatement());
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}

		ResultSet resultSet = null;
		String query = "SELECT ProdottoID, Nome, Scadenza FROM Magazzino";
		try {
			resultSet = ct.getStatement().executeQuery(query);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		try {
			while (resultSet.next()) {
				System.out.println("Id: " + resultSet.getString("ProdottoID") + "| Nome: " + resultSet.getString("Nome")
						+ "| Scadenza: " + resultSet.getString("Scadenza"));

			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		ct.close();

	}

	public boolean login(String nomeutente, String password) {
		ResultSet rs = null;

		Connectiontest ct = new Connectiontest(
				"C:\\Users\\megan\\OneDrive\\Documents\\GitHub\\EasyDhack\\DhackFar\\localdb.db");
		ct.connect();

		try {
			ct.setStatement(ct.getConnection().createStatement());
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}

		String query = "SELECT Nome FROM auth";

		try {
			rs = ct.getStatement().executeQuery(query);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		ArrayList<String> nomi = new ArrayList<>();

		try {
			while (rs.next()) {
				nomi.add(rs.getString("Nome"));
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		boolean corretto = false;
		boolean flagnome = nomi.contains(nomeutente);
		boolean flagpassword;
		if (flagnome) {
			String pass = null;
			String querypassword = "SELECT Password FROM auth WHERE Nome='" + nomeutente + "'";
			try {
				rs = ct.getStatement().executeQuery(querypassword);
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

			try {
				pass = rs.getString("Password");
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

			flagpassword = pass.equals(password);
			if (flagpassword) {
				corretto = true;
			}
		}

		ct.close();
		return corretto;
	}

}
// ----------- << class.extras@AAAAAAGFyotJtauBLeE= >>
// ----------- >>
