/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package persone;

import java.util.ArrayList;

import org.apache.commons.lang.RandomStringUtils;

// ----------- << imports@AAAAAAGFyo3C16vtYQ0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFyo3C16vtYQ0= >>
// ----------- >>
public class Proprietario extends User {

	private ArrayList<Fornitore> listaFornitori;
	private ArrayList<Dipendente> listaDipendenti;

	public Proprietario(String UserID, String Nome, String Cognome, String Password,
			ArrayList<Fornitore> listaFornitori) {
		super(UserID, Nome, Cognome, Password);
		this.listaFornitori = listaFornitori;
	}

	public ArrayList<Fornitore> getListaFornitori() {
		return listaFornitori;
	}

	public ArrayList<Dipendente> getListaDipendenti() {
		return listaDipendenti;
	}

	public void assignPassword(Dipendente dipendente) {
		dipendente.setPassword(RandomStringUtils.randomAlphanumeric(10));
	}

	public void addFornitore(Fornitore fornitore) {
		listaFornitori.add(fornitore);
	}

	public void assumiDipendente(Dipendente dipendente) {
		listaDipendenti.add(dipendente);
	}
// ----------- << class.extras@AAAAAAGFyo3C16vtYQ0= >>
// ----------- >>

}