/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package persone;

import java.sql.SQLException;

import com.archetype.Package.Magazzino;
import com.archetype.Package.Ordine;
import com.archetype.Package.Prodotto;

import connectingdb.Connectiontest;
import prog.io.ConsoleInputManager;

// ----------- << imports@AAAAAAGFyotJtauBLeE= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFyotJtauBLeE= >>
// ----------- >>
public class User {

	private String UserID;
	private String Nome;
	private String Cognome;
	private String Password;

	public User(String UserID, String Nome, String Cognome, String Password) {
		this.UserID = UserID;
		this.Nome = Nome;
		this.Cognome = Cognome;
		this.Password = Password;
	}

	// gettersandsetters
	public String getUserID() {
		return UserID;
	}

	public String getNome() {
		return Nome;
	}

	public String getCognome() {
		return Cognome;
	}

	public String getPassword() {
		return Password;
	}

	public void setPassword(String password) {
		Password = password;
	}

	// methods
	public void nuovoOrdine(Ordine o, Magazzino m) {

	}

	public void visualizzaOrdini(Magazzino m) {
		System.out.println(m.getListaOrdini());
	}

	public void visualizzaGiacenze(Magazzino m) {
		for (Prodotto prodotto : m.getListaProdotti()) {
			System.out.println("Nome prodotto: " + prodotto.getNome() + " , giacenza: " + prodotto.getQta());
		}
	}

	public void visualizzaScadenze(Magazzino m) {
		for (Prodotto prodotto : m.getListaProdotti()) {
			System.out.println("Nome prodotto: " + prodotto.getNome() + " , giacenza: " + prodotto.getScadenza());
		}
	}

	public void login() {
		ConsoleInputManager in = new ConsoleInputManager();
		System.out.println("Inserire nome utente: ");
		String nomeinserito = in.readLine();
		Connectiontest ct = new Connectiontest("C:\\Users\\megan\\Downloads\\sqlite\\sqlite\\auth.db");
		ct.connect();

		try {
			ct.setStatement(ct.getConnection().createStatement());
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		String query = "CONTAINS" + nomeinserito;
		try {
			ct.getStatement().execute(query);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

}
// ----------- << class.extras@AAAAAAGFyotJtauBLeE= >>
// ----------- >>
