/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package persone;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import com.archetype.Package.Magazzino;
import com.archetype.Package.Ordine;
import com.archetype.Package.Prodotto;

import connectingdb.Connectiontest;
import prog.io.ConsoleInputManager;

// ----------- << imports@AAAAAAGFyotJtauBLeE= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFyotJtauBLeE= >>
// ----------- >>
public class User {

	private String UserID;
	private String Nome;
	private String Cognome;
	private String Password;

	public User(String UserID, String Nome, String Cognome, String Password) {
		this.UserID = UserID;
		this.Nome = Nome;
		this.Cognome = Cognome;
		this.Password = Password;
	}

	// gettersandsetters
	public String getUserID() {
		return UserID;
	}

	public String getNome() {
		return Nome;
	}

	public String getCognome() {
		return Cognome;
	}

	public String getPassword() {
		return Password;
	}

	public void setPassword(String password) {
		Password = password;
	}

	// methods
	public void nuovoOrdine(Ordine o, Magazzino m) {

	}

	public void visualizzaOrdini(Magazzino m) {
		System.out.println(m.getListaOrdini());
	}

	public void visualizzaGiacenze(Magazzino m) {
		for (Prodotto prodotto : m.getListaProdotti()) {
			System.out.println("Nome prodotto: " + prodotto.getNome() + " , giacenza: " + prodotto.getQta());
		}
	}

	public void visualizzaScadenze(Magazzino m) {
		for (Prodotto prodotto : m.getListaProdotti()) {
			System.out.println("Nome prodotto: " + prodotto.getNome() + " , giacenza: " + prodotto.getScadenza());
		}
	}

	public void login() {
		ResultSet rs = null;

		Connectiontest ct = new Connectiontest(
				"C:\\Users\\megan\\OneDrive\\Documents\\GitHub\\EasyDhack\\EasyDhack\\auth.db");
		ct.connect();

		try {
			ct.setStatement(ct.getConnection().createStatement());
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}

		String query = "SELECT Nome FROM auth";

		try {
			rs = ct.getStatement().executeQuery(query);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		ArrayList<String> nomi = new ArrayList<>();

		try {
			while (rs.next()) {
				nomi.add(rs.getString("Nome"));
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		ConsoleInputManager in = new ConsoleInputManager();
		String nomeinserito = null;
		boolean flagnomeutente = false;
		while (!flagnomeutente) {
			System.out.println("Inserire nome utente: ");
			nomeinserito = in.readLine();

			for (String string : nomi) {
				if (nomeinserito.equals(string))
					flagnomeutente = true;
			}
		}

		System.out.println("Nome utente corretto. Inserire password: ");
		String pass = null;
		String querypassword = "SELECT Password FROM auth WHERE Nome='" + nomeinserito + "'";
		try {
			rs = ct.getStatement().executeQuery(querypassword);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		try {
			pass = rs.getString("Password");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		boolean flagpassword = false;
		while (!flagpassword) {
			System.out.println("Inserire password: ");
			String passwordinserita = in.readLine();
			if (passwordinserita == pass) {
				flagpassword = true;
			}
		}

		ct.close();
	}

}
// ----------- << class.extras@AAAAAAGFyotJtauBLeE= >>
// ----------- >>
