/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Package1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGFyqUhpMenf8U= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFyqUhpMenf8U= >>
// ----------- >>
public class ListaDipendenti {
    // ----------- << attribute.annotations@AAAAAAGFyqVzysfRh3E= >>
    // ----------- >>
    private ArrayList ListaDipendenti;

    // ----------- << attribute.annotations@AAAAAAGFyqaIt8hM4ps= >>
    // ----------- >>
    private Set<Dipendente>  = new HashSet<>();

    public ArrayList getListaDipendenti() {
        return ListaDipendenti;
    }

    public Set<Dipendente> get() {
        return ;
    }

    public void setListaDipendenti(ArrayList ListaDipendenti) {
        this.ListaDipendenti = ListaDipendenti;
    }

    public void link(Dipendente _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void unlink(Dipendente _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Dipendente _, Iterator<Dipendente> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAGFyqUhpMenf8U= >>
// ----------- >>
}