/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Package1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGFyotJtauBLeE= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFyotJtauBLeE= >>
// ----------- >>
public class User extends Personale {
    // ----------- << attribute.annotations@AAAAAAGFyo4kMKwqbz4= >>
    // ----------- >>
    private String UserID;

    // ----------- << attribute.annotations@AAAAAAGFypLFH6w1COc= >>
    // ----------- >>
    private String Nome;

    // ----------- << attribute.annotations@AAAAAAGFypL8kaw8EB0= >>
    // ----------- >>
    private String Cognome;

    // ----------- << attribute.annotations@AAAAAAGFypNt6KxDROs= >>
    // ----------- >>
    private String Password;

    // ----------- << attribute.annotations@AAAAAAGFz/ThbA8zs5U= >>
    // ----------- >>
    private Fornitore ;

    public String getUserID() {
        return UserID;
    }

    public String getNome() {
        return Nome;
    }

    public String getCognome() {
        return Cognome;
    }

    public String getPassword() {
        return Password;
    }

    public Fornitore get() {
        return ;
    }

    public void setUserID(String UserID) {
        this.UserID = UserID;
    }

    public void setNome(String Nome) {
        this.Nome = Nome;
    }

    public void setCognome(String Cognome) {
        this.Cognome = Cognome;
    }

    public void setPassword(String Password) {
        this.Password = Password;
    }

    public void set(Fornitore ) {
        this. = ;
    }

    public void link(Fornitore _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAGFyrDZLdjXTQE= >>
    // ----------- >>
    public void nuovoOrdine() {
    // ----------- << method.body@AAAAAAGFyrDZLdjXTQE= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGFz/cv7RRwNbM= >>
    // ----------- >>
    public void visualizzaOrdini() {
    // ----------- << method.body@AAAAAAGFz/cv7RRwNbM= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGF7+aeWtv1U00= >>
    // ----------- >>
    public void visualizzaGiacenze() {
    // ----------- << method.body@AAAAAAGF7+aeWtv1U00= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGF7+b4P9xWJMY= >>
    // ----------- >>
    public void visualizzaScadenze() {
    // ----------- << method.body@AAAAAAGF7+b4P9xWJMY= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGFyotJtauBLeE= >>
// ----------- >>
}