/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package uml.Package1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGFyp9N1McFlnE= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFyp9N1McFlnE= >>
// ----------- >>
public abstract class Personale {
// ----------- << class.extras@AAAAAAGFyp9N1McFlnE= >>
// ----------- >>
}